version: "3"

services:

  php:
    environment:
      DRUPAL_ENV: $DRUPAL_ENV
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      # Linux correct permission files.
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    volumes:
    - $PROJECT_DOCROOT:/var/www/html:cached

  nginx:
    environment:
      # Linux correct permission files.
      NGINX_USER: wodby
    volumes:
    - $PROJECT_DOCROOT:/var/www/html:cached

  apache:
    environment:
      # Linux correct permission files.
      APACHE_USER: wodby
      APACHE_GROUP: wodby
    volumes:
    - $PROJECT_DOCROOT:/var/www/html:cached

  mariadb:
    # Expose port of database
    ports:
    - 3306:3306

  redis:
    container_name: "${PROJECT_NAME}_redis"
    image: wodby/redis:$REDIS_TAG

  phpqa:
    image: lucacracco/phpqa:version-2.2
    command: 'tail -f /dev/null'
    container_name: "${PROJECT_NAME}_qa"
    volumes:
    - $PROJECT_DOCROOT:/var/www/html:cached

  traefik:
    ports:
    - '8000:80'
    - '8080:8080' # Dashboard